### ISSUE TITLE
When I create a new `cls-bluebird` context, it fails when require Bluebird

### ISSUE THREAD

**Issue by heortizr** [instana/nodejs-sensor#151]
I'm getting an error in my app when I create a new `cls-bluebird` context, I made an snippet to reproduce it, this snippet works with `instana-nodejs-sensor@1.64.0`, but when I update to `instana-nodejs-sensor@1.65.0` it fails,

Code:
```javascript
require('instana-nodejs-sensor')();
var createNamespace = require('cls-hooked').createNamespace;

const clsBluebird = require('cls-bluebird');

createNamespace('test');
clsBluebird(process.namespaces['test']);
console.log(process.namespaces);
```

Dependencies
```bash
test@1.0.0 /Users/huortiz/dev/sandbox/test
├── bluebird@3.5.5
├── cls-bluebird@2.1.0
├── cls-hooked@4.2.2
└── instana-nodejs-sensor@1.65.0
```

Output
```bash
/Users/huortiz/dev/sandbox/test/node_modules/cls-bluebird/lib/index.js:48
                if (!Promise) throw new Error('Could not require Bluebird');
                              ^

Error: Could not require Bluebird
    at patchBluebird (/Users/huortiz/dev/sandbox/test/node_modules/cls-bluebird/lib/index.js:48:23)
    at Object.<anonymous> (/Users/huortiz/dev/sandbox/test/instana-sensor.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```
this trace could help 
```bash
TypeError: require(...) is not a function
    at patchBluebird (/Users/huortiz/dev/sandbox/test/node_modules/@instana/core/src/tracing/instrumentation/control_flow/bluebird.js:19:26)
    at Function.patchedModuleLoad [as _load] (/Users/huortiz/dev/sandbox/test/node_modules/@instana/core/src/util/requireHook.js:58:36)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/huortiz/dev/sandbox/test/node_modules/cls-bluebird/lib/index.js:15:13)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.patchedModuleLoad [as _load] (/Users/huortiz/dev/sandbox/test/node_modules/@instana/core/src/util/requireHook.js:25:32)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/huortiz/dev/sandbox/test/instana-sensor.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
```

I know, I can use `clsBluebird(ns, Promise)` instead of `clsBluebird(ns)`, but, why `require()` is not a function? Is there an issue?

**Comment by heortizr** [comment]
I forgot mentioned, but it fails on `instana-nodejs-sensor@1.68.3` too

**Comment by basti1302** [comment]
Thanks for reporting. Fixed via #152 and 27663d9.

**Comment by basti1302** [comment]
The fix has landed in 1.68.4.
